/**
 * Example usage of the Multi-LLM Engine Wrapper
 * 
 * Shows how to use task-specific routing with automatic fallback
 */

const { executeWithEngine, ROUTING_RULES } = require('./agent_engine_wrapper');

// === Example 1: X/Twitter Thread (uses Grok) ===
async function createXThread(topic) {
    const result = await executeWithEngine('x_thread', `
    Create a viral X thread about: ${topic}
    
    Requirements:
    - 5-7 tweets
    - Hook in first tweet
    - Contrarian take
    - End with a call to action
    - Use Fikanova's edgy brand voice
  `);

    console.log(`[X Thread] Generated by: ${result.engine} (${result.model})`);
    console.log(`[X Thread] Cost: $${result.cost.toFixed(4)}`);
    if (result.fallback) console.log('[X Thread] Note: Used fallback engine');

    return result.result.text;
}

// === Example 2: LinkedIn Newsletter (uses ChatGPT) ===
async function createLinkedInNewsletter(topic, keyPoints) {
    const result = await executeWithEngine('linkedin_newsletter', `
    Write a professional LinkedIn newsletter about: ${topic}
    
    Key points to cover:
    ${keyPoints.map(p => `- ${p}`).join('\n')}
    
    Requirements:
    - Professional but engaging tone
    - 800-1200 words
    - Include a compelling headline
    - Add section headers
    - End with discussion question
  `);

    console.log(`[LinkedIn] Generated by: ${result.engine} (${result.model})`);
    console.log(`[LinkedIn] Cost: $${result.cost.toFixed(4)}`);

    return result.result.text;
}

// === Example 3: PRD Generation (uses Claude) ===
async function generatePRD(brief) {
    const result = await executeWithEngine('prd', `
    Generate a Product Requirement Document for:
    ${brief}
    
    Follow Fikanova PRD template with:
    - Executive Summary
    - Problem Statement
    - User Stories
    - Technical Requirements
    - Success Metrics
  `);

    console.log(`[PRD] Generated by: ${result.engine} (${result.model})`);
    return result.result.text;
}

// === Example 4: Quick Summary (uses Gemini - cost optimized) ===
async function summarize(text) {
    const result = await executeWithEngine('summary', `
    Summarize this in 3 bullet points:
    ${text}
  `);

    console.log(`[Summary] Generated by: ${result.engine} (cost: $${result.cost.toFixed(6)})`);
    return result.result.text;
}

// === Example 5: Spelling Check (uses Gemini Nano - cheapest) ===
async function spellCheck(text) {
    const result = await executeWithEngine('spelling', `
    Fix any spelling and grammar errors in this text. Return only the corrected text:
    ${text}
  `);

    console.log(`[Spellcheck] Used cheapest engine: ${result.engine}`);
    return result.result.text;
}

// === Demo with fallback ===
async function demo() {
    console.log('=== Multi-LLM Engine Demo ===\n');

    console.log('Routing rules:');
    console.log(ROUTING_RULES);
    console.log('\n');

    try {
        // This will use Grok for X, ChatGPT for LinkedIn, etc.
        // If any is unavailable, it automatically falls back

        const xThread = await createXThread('The Termite Stack - Why AI agents need to eat their own dogfood');
        console.log('\n--- X Thread ---\n', xThread.substring(0, 500), '...\n');

        const newsletter = await createLinkedInNewsletter('Building AI-First Companies in Africa', [
            'The mobile-first advantage',
            'Sheng as a unique differentiator',
            'M-Pesa integration patterns'
        ]);
        console.log('\n--- LinkedIn Newsletter ---\n', newsletter.substring(0, 500), '...\n');

    } catch (error) {
        console.error('Error:', error.message);
    }
}

// Run demo if called directly
if (require.main === module) {
    demo();
}

module.exports = {
    createXThread,
    createLinkedInNewsletter,
    generatePRD,
    summarize,
    spellCheck
};
